version: '3'
services:
  bidder-api:
    container_name: bidder-server
    build:
      context: .
      dockerfile: Dockerfile
    image: bidder-server
    ports:
      - '3002:3002'
    networks:
      - bidder-net-work

networks:
  bidder-net-work:
    name: rtb_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
